### PR TITLE
LUA: update regexp string to only get " LUA "

### PR DESCRIPTION
**Pull request by Woovie**
This should fix issue #1

### CODE REVIEW

**Comment by Woovie** [comment]
Actually, I just realized this won't capture "LUA" and nothing else, but I'm not sure that's important. It also won't capture "LUA sucks" or "I hate LUA", which is a bit more important. I'll revise this.

**Comment by Woovie** [comment]
Still not quite right. It's missing some. The regex site I was using to test was matching line returns... Testing further.

**Comment by qaisjp** [comment]
Would just `\WLUA\W` work?

**Comment by Woovie** [comment]
No, but I made a solution!

(^|\W)LUA($|\W)

Screen Shot 2019-07-09 at 8 40 06 PM

**Pull request merged**
